# Generated by Django 5.1.4 on 2024-12-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_revenue_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finances.person'),
        ),
    ]
